### ISSUE TITLE
1.3.3 install broken, Ubuntu 16.04, "'pytest distribution was not found and is required by pkgconfig"

### ISSUE THREAD

**Issue by spacez320** [mehcode/python-xmlsec#103]
Full stack trace:

```
root@b7c71b47fd67:/# pip install xmlsec==1.3.3
Collecting xmlsec==1.3.3
  Using cached https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz                                                                                                                                        
    Complete output from command python setup.py egg_info:
    Building lxml version 4.3.3.
    Building without Cython.
    Using build configuration of libxslt 1.1.28

    Installed /tmp/pip-install-eo9_nzz5/xmlsec/.eggs/lxml-4.3.3-py3.5-linux-x86_64.egg
    Searching for pkgconfig
    Reading https://pypi.python.org/simple/pkgconfig/
    Best match: pkgconfig 1.5.0
    Downloading https://files.pythonhosted.org/packages/43/44/0eda08389fbf1c66b6c63f072bdfc043c90504a4aedb5d2bc6f9b3921db9/pkgconfig-1.5.0.tar.gz#sha256=cc283fe8ff1c2bbc49c6d81a7ad33270d62459199b012147fe47a0bd9224f5c9                                                            
    Processing pkgconfig-1.5.0.tar.gz
    Writing /tmp/easy_install-_qtc96sb/pkgconfig-1.5.0/setup.cfg
    Running pkgconfig-1.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_qtc96sb/pkgconfig-1.5.0/egg-dist-tmp-hfpky5p9
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    zip_safe flag not set; analyzing archive contents...
    Moving pkgconfig-1.5.0-py3.5.egg to /tmp/pip-install-eo9_nzz5/xmlsec/.eggs

    Installed /tmp/pip-install-eo9_nzz5/xmlsec/.eggs/pkgconfig-1.5.0-py3.5.egg
    Searching for pytest<4.0.0,>=3.8.2
    Reading https://pypi.python.org/simple/pytest/
    Best match: pytest 3.10.1
    Downloading https://files.pythonhosted.org/packages/b5/96/37011e484665fab8b51add4f707d2aa28f1a06c68dd1c8a50e03551693b3/pytest-3.10.1.tar.gz#sha256=e246cf173c01169b9617fc07264b7b1316e78d7a650055235d6d897bc80d9660                                                              
    Processing pytest-3.10.1.tar.gz
    Writing /tmp/easy_install-888tz8uo/pytest-3.10.1/setup.cfg
    Running pytest-3.10.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-888tz8uo/pytest-3.10.1/egg-dist-tmp-dh4vqj7l
    warning: no previously-included files found matching 'pyproject.toml'

    Installed /tmp/easy_install-888tz8uo/pytest-3.10.1/.eggs/setuptools-40.8.0-py3.5.egg
    Searching for setuptools-scm
    Reading https://pypi.python.org/simple/setuptools-scm/
    Best match: setuptools-scm 3.2.0
    Downloading https://files.pythonhosted.org/packages/88/8c/71711f2742bc04f62dcf6391c0c76b0fe985d7a100667ea22e0a5f9cf183/setuptools_scm-3.2.0-py3.5.egg#sha256=3625c1f1cdc576ab0ee7acaa45123f84d323fd4857227091206560cb50df4771                                                    
    Processing setuptools_scm-3.2.0-py3.5.egg
    Moving setuptools_scm-3.2.0-py3.5.egg to /tmp/easy_install-888tz8uo/pytest-3.10.1/.eggs

    Installed /tmp/easy_install-888tz8uo/pytest-3.10.1/.eggs/setuptools_scm-3.2.0-py3.5.egg
    warning: install_lib: 'build/lib' does not exist -- no Python modules to install

    zip_safe flag not set; analyzing archive contents...
    Moving UNKNOWN-3.10.1-py3.5.egg to /tmp/pip-install-eo9_nzz5/xmlsec/.eggs

    Installed /tmp/pip-install-eo9_nzz5/xmlsec/.eggs/UNKNOWN-3.10.1-py3.5.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-eo9_nzz5/xmlsec/setup.py", line 60, in <module>
        'Topic :: Text Processing :: Markup :: XML'
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pytest<4.0.0,>=3.8.2' distribution was not found and is required by pkgconfig
```

Specifically installing pytest does not help.

**Comment by hoefling** [comment]
Looks like this is caused by matze/pkgconfig#43. Omitting `pkgconfig==1.5.0` should resolve this.
