### ISSUE TITLE
Cannot install package xmlsec on RHEL7.6

### ISSUE THREAD

**Issue by ragnarokatz** [mehcode/python-xmlsec#107]
Hello,

I'm trying to install the python package `python3-saml`, which depends on python libraries `xmlsec` and `pkgconfig`.

system information:
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.6 (Maipo)
Release:        7.6
Codename:       Maipo
```

error I'm getting when I do pip install **xmlsec**:
```
Building wheel for xmlsec (setup.py) ... error
  ERROR: Complete output from command /apps/conda/envs/python3-saml/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-h8tggu_7/xmlsec/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-jzjpfpzv --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-h8tggu_7/xmlsec/setup.py", line 60, in <module>
      'Topic :: Text Processing :: Markup :: XML'
    File "/apps/conda/envs/python3-saml/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/apps/conda/envs/python3-saml/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/apps/conda/envs/python3-saml/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/apps/conda/envs/python3-saml/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/apps/conda/envs/python3-saml/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/apps/conda/envs/python3-saml/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/apps/conda/envs/python3-saml/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/apps/conda/envs/python3-saml/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/apps/conda/envs/python3-saml/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/apps/conda/envs/python3-saml/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-h8tggu_7/xmlsec/setup.py", line 11, in run
      self.patch_options()
    File "/tmp/pip-install-h8tggu_7/xmlsec/setup.py", line 16, in patch_options
      ext.define_macros.extend(xmlsec_setupinfo.define_macros())
    File "/tmp/pip-install-h8tggu_7/xmlsec/xmlsec_setupinfo.py", line 48, in define_macros
      macros.extend(xmlsec_config()['define_macros'])
    File "/tmp/pip-install-h8tggu_7/xmlsec/xmlsec_setupinfo.py", line 111, in xmlsec_config
      __XMLSEC_CONFIG = load_xmlsec1_config()
    File "/tmp/pip-install-h8tggu_7/xmlsec/xmlsec_setupinfo.py", line 164, in load_xmlsec1_config
      config = pkgconfig.parse('xmlsec1')
    File "/apps/conda/envs/python3-saml/lib/python3.6/site-packages/pkgconfig/pkgconfig.py", line 248, in parse
      _raise_if_not_exists(package)
    File "/apps/conda/envs/python3-saml/lib/python3.6/site-packages/pkgconfig/pkgconfig.py", line 103, in _raise_if_not_exists
      raise PackageNotFoundError(package)
  pkgconfig.pkgconfig.PackageNotFoundError: xmlsec1 not found
```

I already did `yum install pkg-config xmlsec1-openssl xmlsec1 libxml2 libxml2-devel xmlsec1-devel xmlsec1-openssl-devel libtool-ltdl-devel`.

However, package `xmlsec1` does not come with a .pc file under /usr/lib64/pkgconfig/ folder. I tried manually creating one, but then it points me to a bunch of other missing dependencies that also do not have .pc files created.

Version hosted on pypi for xmlsec is 1.3.3. I also tried downloading python-xmlsec-1.3.6.zip manually and building wheel file from source. Also does not work, I'm getting the same error `xmlsec1 not found`

Any ideas?

**Comment by distortedsignal** [comment]
Hey @ragnarokatz, have any insight on this? I see you closed your own issue - how did you get past this?

**Comment by ragnarokatz** [comment]
Hey,

I think I missed a package in the long list:

yum install pkg-config xmlsec1-openssl xmlsec1 libxml2 libxml2-devel
xmlsec1-devel xmlsec1-openssl-devel libtool-ltdl-devel

I just ran this again and made sure every single one of them was installed.
Then it worked.

**Comment by distortedsignal** [comment]
Thanks.

I feel like I was in a [DenverCoder9](https://xkcd.com/979/) scenario - I'll try this out!

**Comment by anoasis** [comment]
I am encountering the same issue while installing your xmlsec package in my RHEL7 docker container.

I've checked every single dependency installed and tried manual installation as well. Still no luck.

Anyone has a resolution on this?

`root@docker[e5d232df0d1c]:/libxml2-2.9.1> yum install xmlsec1-openssl
Loaded plugins: ovl
Package xmlsec1-openssl-1.2.20-7.el7_4.x86_64 already installed and latest version
Nothing to do
root@docker[e5d232df0d1c]:/libxml2-2.9.1> yum install xmlsec1
Loaded plugins: ovl
Package xmlsec1-1.2.20-7.el7_4.x86_64 already installed and latest version
Nothing to do
root@docker[e5d232df0d1c]:/libxml2-2.9.1> yum install libxml2
Loaded plugins: ovl
Package libxml2-2.9.1-6.el7_2.3.x86_64 already installed and latest version
Nothing to do
root@docker[e5d232df0d1c]:/libxml2-2.9.1> yum install libxml2-devel
Loaded plugins: ovl
Package libxml2-devel-2.9.1-6.el7_2.3.x86_64 already installed and latest version
Nothing to do
root@docker[e5d232df0d1c]:/libxml2-2.9.1> yum install xmlsec1-devel
Loaded plugins: ovl
No package xmlsec1-devel available.
Error: Nothing to do
root@docker[e5d232df0d1c]:/libxml2-2.9.1> yum install xmlsec1-openssl-devel
Loaded plugins: ovl
No package xmlsec1-openssl-devel available.
Error: Nothing to do
Loaded plugins: ovlf0d1c]:/libxml2-2.9.1> yum install libtool-ltdl-devel
Package libtool-ltdl-devel-2.4.2-22.el7_3.x86_64 already installed and latest version
Nothing to do
root@docker[e5d232df0d1c]:/libxml2-2.9.1> python3 -m pip install xmlsec
Collecting xmlsec
  Using cached https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz
Requirement already satisfied: pkgconfig in /usr/local/lib/python3.6/site-packages (from xmlsec) (1.5.1)
Requirement already satisfied: lxml>=3.0 in /usr/local/lib64/python3.6/site-packages (from xmlsec) (4.4.1)
Installing collected packages: xmlsec
  Running setup.py install for xmlsec ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zd7dbesy/xmlsec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zd7dbesy/xmlsec/setup.py'"'"';f=getattr(tokenize, '"'"'op
en'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v4fgbwb5/install-record.txt --single-version-externally-mana
ged --compile
         cwd: /tmp/pip-install-zd7dbesy/xmlsec/
    Complete output (44 lines):
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zd7dbesy/xmlsec/setup.py", line 60, in <module>
        'Topic :: Text Processing :: Markup :: XML'
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 556, in run
        self.run_command('build')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-zd7dbesy/xmlsec/setup.py", line 11, in run
        self.patch_options()
      File "/tmp/pip-install-zd7dbesy/xmlsec/setup.py", line 16, in patch_options
        ext.define_macros.extend(xmlsec_setupinfo.define_macros())
      File "/tmp/pip-install-zd7dbesy/xmlsec/xmlsec_setupinfo.py", line 48, in define_macros
        macros.extend(xmlsec_config()['define_macros'])
      File "/tmp/pip-install-zd7dbesy/xmlsec/xmlsec_setupinfo.py", line 111, in xmlsec_config
        __XMLSEC_CONFIG = load_xmlsec1_config()
      File "/tmp/pip-install-zd7dbesy/xmlsec/xmlsec_setupinfo.py", line 164, in load_xmlsec1_config
        config = pkgconfig.parse('xmlsec1')
      File "/usr/local/lib/python3.6/site-packages/pkgconfig/pkgconfig.py", line 248, in parse
        _raise_if_not_exists(package)
      File "/usr/local/lib/python3.6/site-packages/pkgconfig/pkgconfig.py", line 103, in _raise_if_not_exists
        raise PackageNotFoundError(package)
    pkgconfig.pkgconfig.PackageNotFoundError: xmlsec1 not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zd7dbesy/xmlsec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zd7dbesy/xmlsec/setup.py
'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-v4fgbwb5/install-record.txt
 --single-version-externally-managed --compile Check the logs for full command output.`

**Comment by crankd** [comment]
Adding -y to yum install fixed it for me.
```dockerfile
yum clean all && yum install -y pkg-config xmlsec1-openssl xmlsec1 libxml2 libxml2-devel xmlsec1-devel xmlsec1-openssl-devel libtool-ltdl-devel
```

**Comment by todaynowork** [comment]
> I also had encountered the same issue while installing your xmlsec package in my RHEL7 docker container. My solution was the proper PKG_CONFIG_PATH config on top of the manual libs(xmlsec1+libxml2) installation.

Hello, can you share your solution in detail? Thanks.
