### ISSUE TITLE
Pip install failing on Ubuntu 12.04, Python 3.4.3

### ISSUE THREAD

**Issue by daaray** [mehcode/python-xmlsec#11]
This is the first time I have attempted to utilize this library, so hopefully I am missing something easy.

I installed the dependencies:

`apt-get install libxml2-dev libxmlsec1-dev`

A `pip install xmlsec==0.3.3` generates the following error:

```
[...]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DXMLSEC_NO_GOST=1 -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_OPENSSL_098=1 -DXMLSEC_CRYPTO_OPENSSL=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_CRYPTO=\\openssl\\ -DXMLSEC_NO_SIZE_T= -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -Isrc -I/home/daaray/.virtualenvs/market_builder/build/xmlsec/lxml-3.5.0b1-py3.4-linux-x86_64.egg/lxml/includes -I/home/daaray/.virtualenvs/market_builder/build/xmlsec/lxml-3.5.0b1-py3.4-linux-x86_64.egg/lxml -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/usr/include/python3.4m -I/home/daaray/.virtualenvs/market_builder/include/python3.4m -c src/xmlsec/constants.c -o build/temp.linux-x86_64-3.4/src/xmlsec/constants.o -DXMLSEC_CRYPTO_OPENSSL=1

src/xmlsec/constants.c: In function ‘PyInit_constants’:

src/xmlsec/constants.c:2419:61: error: ‘xmlSecTransformEcdsaSha1Id’ undeclared (first use in this function)

src/xmlsec/constants.c:2419:61: note: each undeclared identifier is reported only once for each function it appears in

src/xmlsec/constants.c:2431:61: error: ‘xmlSecTransformEcdsaSha224Id’ undeclared (first use in this function)

src/xmlsec/constants.c:2443:61: error: ‘xmlSecTransformEcdsaSha256Id’ undeclared (first use in this function)

src/xmlsec/constants.c:2455:61: error: ‘xmlSecTransformEcdsaSha384Id’ undeclared (first use in this function)

src/xmlsec/constants.c:2467:61: error: ‘xmlSecTransformEcdsaSha512Id’ undeclared (first use in this function)

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Please advise.

**Comment by mehcode** [comment]
Try installing the latest version of cython first. 

```
pip install "cython==0.23.3"
```

---

This seems to be a recent problem from the recent release. It's not supposed to need an install of cython (it should install it using install requires).

**Comment by mehcode** [comment]
Nope. That didn't fix it for me. 

Hmm..

For now, ping your version to `0.3.2`

```
pip install "xmlsec==0.3.2"
```

**Comment by mehcode** [comment]
What version of gcc are you using? I can reproduce the failure with `4.8.2` but it installs successfully with `5.2.0`.

**Comment by daaray** [comment]
`4.6.3`; I will update. Thanks for the quick responses.

**Comment by mehcode** [comment]
Any ideas @bgaifullin / @changjej  ? I'd like to keep gcc 4.x compatibiltiy.

@daaray For the record, v0.3.2 installs fine on gcc 4.x and has the same features as v0.3.3. The release was intended to support the newest version of cython in combination with gcc 5.x.

**Comment by mehcode** [comment]
Apparently I'm crazy -- make that `0.3.1`. `0.3.2` doesn't exist.

**Comment by daaray** [comment]
Ah, ok...I will go that route 1st; installing v0.3.1. Thanks again.

**Comment by daaray** [comment]
Reporting back...with `gcc v4.6.3` a `pip install xmlsec==0.3.1` resulted in the following for me:

```
src/xmlsec/enc.c: In function '__pyx_import_star_set':

src/xmlsec/enc.c:3384:37: error: lvalue required as left operand of assignment

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by mehcode** [comment]
Try uninstalling `cython` (hopefully you're in a virtualenv). Sorry this has been so hard to install. Will be working on it.

**Comment by daaray** [comment]
hrm, a `pip freeze` inside the virtualenv does not list Cython at all.

**Comment by mehcode** [comment]
This is broken for me too in a deployment script. Trying to come up with a resolution.

**Comment by mehcode** [comment]
I'm currently running it now with a force install of cython as:

```
pip install "cython<0.23"
```

**Comment by mehcode** [comment]
This seems to work for me. @daaray ?

**Comment by daaray** [comment]
Yes, `xmlsec v0.3.1` installed successfully with `Cython<0.23` in play using `gcc 4.6.3`. Thanks!

**Comment by balavec** [comment]
I am running gcc version 4.4.7 and can not install it even with:

    pip install "cython<0.23"
    pip install "xmlsec==0.3.1"

**Comment by pitbulk** [comment]
Fresh Ubuntu 14.04 with dependences resolved:
```
Python 2.7.6
gcc (Ubuntu 4.8.4-2ubuntu1~14.04)
pip 7.1.2
setuptools 18.7.1
libxmlsec1 1.2.18
libxml2 2.9.1
libxslt 1.1.28
```

I was not able to install xmlsec.

pip install "cython<0.23"
```
Successfully built cython
Installing collected packages: cython
Successfully installed cython-0.22.1
```
Following error when installing xmlsec==0.3.1:
```
Building lxml version 3.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-yWkLxX/xmlsec/setup.py", line 121, in <module>
        make_extension('xmlsec.template'),
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1091, in best_match
        return self.obtain(req, installer)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1103, in obtain
        return installer(requirement)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 639, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 669, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 853, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1081, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1069, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
```
Similar with xmlsec==0.3.3
```
    Complete output from command python setup.py egg_info:
    x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
    Building lxml version 3.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-PVFjyb/xmlsec/setup.py", line 121, in <module>
        make_extension('xmlsec.template'),
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1091, in best_match
        return self.obtain(req, installer)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1103, in obtain
        return installer(requirement)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 639, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 669, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 853, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1081, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1069, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
```

Now with pip install "cython==0.23.3"
```
  Found existing installation: Cython 0.22.1
    Uninstalling Cython-0.22.1:
      Successfully uninstalled Cython-0.22.1
Successfully installed cython-0.23.3
```
pip install "xmlsec==0.3.1"
```
Collecting xmlsec==0.3.1
  Using cached xmlsec-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
    Building lxml version 3.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-nozTIu/xmlsec/setup.py", line 121, in <module>
        make_extension('xmlsec.template'),
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1091, in best_match
        return self.obtain(req, installer)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1103, in obtain
        return installer(requirement)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 639, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 669, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 853, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1081, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1069, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
```

Same with "xmlsec==0.3.3"
```
  Downloading xmlsec-0.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
    Building lxml version 3.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    Compile failed: command 'x86_64-linux-gnu-gcc' failed with exit status 4
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-WF5EyP/xmlsec/setup.py", line 121, in <module>
        make_extension('xmlsec.template'),
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1091, in best_match
        return self.obtain(req, installer)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1103, in obtain
        return installer(requirement)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 639, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 669, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 853, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1081, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/vagrant/Envs/myproject/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1069, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 4
```

**Comment by pitbulk** [comment]
In this case, Its seems that the problem is related to lxml 3.5.0:
```
/tmp/easy_install-Ew8_x0/lxml-3.5.0/temp/xmlXPathInitI_sX_B.c:2:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 main (int argc, char **argv) {
```

**Comment by raghuraju** [comment]
I am also unable to install with this line in the requirements.txt file
```
git+git://github.com/mehcode/python-xmlsec.git
```
connection keeps timing out, may be some access rights issue?

**Comment by mehcode** [comment]
Could everyone here try installing again 

```
pip install xmlsec==0.5.0
```

**Comment by pitbulk** [comment]
@mehcode
My system Ubuntu 14.04.3.   python2.7
I tried xmlsec-0.5.0 and Cython-0.23 . Installation worked but I have a segmentation fault when using
xmlsec

Same happens with xmlsec-0.5.0 and Cython-0.23.4

(I trying it in [python3-saml](https://github.com/onelogin/python3-saml) with the setup.py edited to point those versions. and got the error when executing the python setup.py test  command.

```
testValidateSign (tests.src.OneLogin.saml2_tests.utils_test.OneLogin_Saml2_Utils_Test) ...  segment fault.
```

**Comment by bgaifullin** [comment]
@pitbulk, thank you for report. I will check this.

**Comment by pitbulk** [comment]
Appreciate, let me know if I can help

**Comment by pitbulk** [comment]
@bgaifullin , any progress with that issue?

**Comment by bgaifullin** [comment]
@pitbulk Ive reproduced issue, but I do not found root cause yet.

**Comment by bgaifullin** [comment]
When I run xmlsec tests with same data - no fault. 
When run onelogin tests - fault. :(

**Comment by pitbulk** [comment]
I discovered that maybe is related with lxml and the cython version.

I installed
```
pip install lxml==3.5.0b1
pip install Cython==0.23
```
and I was able to install xmlsec==0.3.0 and python3-saml  and test no failing.

**Comment by bgaifullin** [comment]
@pitbulk, Could you check that #20 works for you, please.

**Comment by pitbulk** [comment]
@bgaifullin bad news

I created a new virtualenv, cloned python3-saml, edited the setup.py
```
 
``` 
so now I point your master branch
```
Searching for xmlsec>=0.3.1
Reading https://github.com/bgaifullin/python-xmlsec/tarball/master
```
xmlsec 0.5.0, Cython 0.23.4, lxml-3.5.0 are used.

Installation worked
```
Installed /home/pitbulk/proyectos/toolkits/python3-saml/venv/lib/python2.7/site-packages/lxml-3.5.0-py2.7-linux-x86_64.egg
Finished processing dependencies for python3-saml==1.0.0
```
but segmentation fault happens on
```
testValidateSign (tests.src.OneLogin.saml2_tests.utils_test.OneLogin_Saml2_Utils_Test) 

segfault at libxmlsec1.so.1.2.20[7f9e82021000+65000]
```

**Comment by bgaifullin** [comment]
@pitbulk thank you. I will continue investigation.

**Comment by bgaifullin** [comment]
@pitbulk You are using xmlsec from pip, the xmlsec from https://github.com/bgaifullin/python-xmlsec has version 0.3.3

root@node-1:~/python3-saml# pip3 show xmlsec
---
Name: xmlsec
Version: 0.3.3
Location: /usr/local/lib/python3.4/dist-packages/xmlsec-0.3.3-py3.4-linux-x86_64.egg
Requires: lxml

Please try to use the following command to install custom version of xmlsec
<your env path>/bin/pip install git+http://github.com/bgaifullin/python-xmlsec

**Comment by bgaifullin** [comment]
@pitbulk I found the reason. As soon as CI has been completed I will merge the fix.

**Comment by bgaifullin** [comment]
@mehcode Please upload new build to pypi.

**Comment by pitbulk** [comment]
I tested, the change solved the issue ;)
