### ISSUE TITLE
Cannot install xmlsec 1.3.3 in a docker container based on oracle linux 7.6

### ISSUE THREAD

**Issue by bhashah** [mehcode/python-xmlsec#113]
Hi, 

I am trying to create a docker image for a python project which uses python3-saml and xmlsec python packages. But, it gives following error when tries to install xmlsec:

Running setup.py install for xmlsec: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /app/venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j3x0_vn6/xmlsec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j3x0_vn6/xmlsec/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-92lr69o3/install-record.txt --single-version-externally-managed --compile --install-headers /app/venv/include/site/python3.7/xmlsec
         cwd: /tmp/pip-install-j3x0_vn6/xmlsec/
    Complete output (44 lines):
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-j3x0_vn6/xmlsec/setup.py", line 60, in <module>
        'Topic :: Text Processing :: Markup :: XML'
      File "/app/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/app/venv/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-j3x0_vn6/xmlsec/setup.py", line 11, in run
        self.patch_options()
      File "/tmp/pip-install-j3x0_vn6/xmlsec/setup.py", line 16, in patch_options
        ext.define_macros.extend(xmlsec_setupinfo.define_macros())
      File "/tmp/pip-install-j3x0_vn6/xmlsec/xmlsec_setupinfo.py", line 48, in define_macros
        macros.extend(xmlsec_config()['define_macros'])
      File "/tmp/pip-install-j3x0_vn6/xmlsec/xmlsec_setupinfo.py", line 111, in xmlsec_config
        __XMLSEC_CONFIG = load_xmlsec1_config()
      File "/tmp/pip-install-j3x0_vn6/xmlsec/xmlsec_setupinfo.py", line 164, in load_xmlsec1_config
        config = pkgconfig.parse('xmlsec1')
      File "/app/venv/lib/python3.7/site-packages/pkgconfig/pkgconfig.py", line 248, in parse
        _raise_if_not_exists(package)
      File "/app/venv/lib/python3.7/site-packages/pkgconfig/pkgconfig.py", line 103, in _raise_if_not_exists
        raise PackageNotFoundError(package)
    pkgconfig.pkgconfig.PackageNotFoundError: xmlsec1 not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: /app/venv/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j3x0_vn6/xmlsec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j3x0_vn6/xmlsec/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-92lr69o3/install-record.txt --single-version-externally-managed --compile --install-headers /app/venv/include/site/python3.7/xmlsec Check the logs for full command output.

My Dockerfile contains:
RUN yum -y install pkgconfig xmlsec1-openssl xmlsec1 libxml2 libxml2-devel libtool-ltdl-devel
RUN pip3.7 install --trusted-host pypi.python.org -r requirements.txt

Please note that xmlsec1-devel xmlsec1-openssl-devel are not found on oracle linux 7.6

**Comment by codedawi** [comment]
Had a similar issue and I needed to change the lib paths to `lib64` to resolve properly. Try setting the `LD_LIBRARY_PATH` and `PKG_CONFIG_PATH` env variables before installing in Dockerfile:
```docker
ENV LD_LIBRARY_PATH="/opt/bb/lib64"
ENV PKG_CONFIG_PATH="/opt/bb/lib64/pkgconfig"
```
You may get away with only updating `LD_LIBRARY_PATH` .

**Comment by hoefling** [comment]
Resort to building a static wheel if your target OS is missing necessary dependencies. See https://github.com/mehcode/python-xmlsec/issues/81#issuecomment-633230184 for details.
