### ISSUE TITLE
Install failure due to missing dependancies, apparently missing explicit dependancy on wheel but actually missing system dependancies.

### ISSUE THREAD

**Issue by josh-marshall-jax** [mehcode/python-xmlsec#115]
When installing in a clean environment, attempts to use `pip` or `poetry` fail due to missing explicit dependency on the `wheel` module.  It looks like a one-line change in `requirements.txt` to include `wheel` should fix the issue.

```
marshjo@marshjo-MacBookPro:/tmp/test$ poetry add python3-saml
Using version ^1.8.0 for python3-saml

Updating dependencies
Resolving dependencies... (0.2s)

Writing lock file


Package operations: 5 installs, 0 updates, 0 removals

  - Installing lxml (4.4.1)
  - Installing pkgconfig (1.5.1)
  - Installing isodate (0.6.0)
  - Installing xmlsec (1.3.3)

[EnvCommandError]
Command ['/home/marshjo/.cache/pypoetry/virtualenvs/test-CHLv_kh8-py3.7/bin/python', '-m', 'pip', 'install', '--no-deps', 'xmlsec==1.3.3'] errored with the following return code 1, and output: 
Collecting xmlsec==1.3.3
  Using cached https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz
Building wheels for collected packages: xmlsec
  Running setup.py bdist_wheel for xmlsec: started
  Running setup.py bdist_wheel for xmlsec: finished with status 'error'
  Complete output from command /home/marshjo/.cache/pypoetry/virtualenvs/test-CHLv_kh8-py3.7/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wq4l4ugu/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-cs114a64 --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for xmlsec
  Running setup.py clean for xmlsec
Failed to build xmlsec
Installing collected packages: xmlsec
  Running setup.py install for xmlsec: started
    Running setup.py install for xmlsec: finished with status 'error'
    Complete output from command /home/marshjo/.cache/pypoetry/virtualenvs/test-CHLv_kh8-py3.7/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wq4l4ugu/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-fh6p88l1/install-record.txt --single-version-externally-managed --compile --install-headers /home/marshjo/.cache/pypoetry/virtualenvs/test-CHLv_kh8-py3.7/include/site/python3.7/xmlsec:
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wq4l4ugu/xmlsec/setup.py", line 60, in <module>
        'Topic :: Text Processing :: Markup :: XML'
      File "/home/marshjo/.cache/pypoetry/virtualenvs/test-CHLv_kh8-py3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/marshjo/.cache/pypoetry/virtualenvs/test-CHLv_kh8-py3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-wq4l4ugu/xmlsec/setup.py", line 11, in run
        self.patch_options()
      File "/tmp/pip-install-wq4l4ugu/xmlsec/setup.py", line 16, in patch_options
        ext.define_macros.extend(xmlsec_setupinfo.define_macros())
      File "/tmp/pip-install-wq4l4ugu/xmlsec/xmlsec_setupinfo.py", line 48, in define_macros
        macros.extend(xmlsec_config()['define_macros'])
      File "/tmp/pip-install-wq4l4ugu/xmlsec/xmlsec_setupinfo.py", line 111, in xmlsec_config
        __XMLSEC_CONFIG = load_xmlsec1_config()
      File "/tmp/pip-install-wq4l4ugu/xmlsec/xmlsec_setupinfo.py", line 164, in load_xmlsec1_config
        config = pkgconfig.parse('xmlsec1')
      File "/home/marshjo/.cache/pypoetry/virtualenvs/test-CHLv_kh8-py3.7/lib/python3.7/site-packages/pkgconfig/pkgconfig.py", line 248, in parse
        _raise_if_not_exists(package)
      File "/home/marshjo/.cache/pypoetry/virtualenvs/test-CHLv_kh8-py3.7/lib/python3.7/site-packages/pkgconfig/pkgconfig.py", line 103, in _raise_if_not_exists
        raise PackageNotFoundError(package)
    pkgconfig.pkgconfig.PackageNotFoundError: xmlsec1 not found
    
    ----------------------------------------
Command "/home/marshjo/.cache/pypoetry/virtualenvs/test-CHLv_kh8-py3.7/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-wq4l4ugu/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-fh6p88l1/install-record.txt --single-version-externally-managed --compile --install-headers /home/marshjo/.cache/pypoetry/virtualenvs/test-CHLv_kh8-py3.7/include/site/python3.7/xmlsec" failed with error code 1 in /tmp/pip-install-wq4l4ugu/xmlsec/
```

**Comment by josh-marshall-jax** [comment]
Did a little more testing, and installing the listed system dependencies fixed the problem, which is not what the above error log suggests.  I'm not sure what exactly should change to make this more apparent, but the error thrown shouldn't be that misleading.

**Comment by swat323** [comment]
@josh-marshall-jax can you please tell me which exact dependencies you are talking about here. That would help me with my issue.

**Comment by josh-marshall-jax** [comment]
I am no longer able to replicate the issue as described.  There still seem to be some odd relations on itself, but it is no longer causing problems for my use case.

**Comment by vishwanathjadhav** [comment]
Try to install the following dependencies and the try it again:

~~~
apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl python3-pip
apt-get install -y  xmlsec1 xmlsec
apt-get install -y  xmlsec1
pip3 install -e .
or 
pip3 install python3-saml
~~~
