### ISSUE TITLE
xmlsec library version mismatch in windows wsl2

### ISSUE THREAD

**Issue by boneVidy** [mehcode/python-xmlsec#162]
xmlsec version:1.3.9
libxmlsec1:1.2.31
libxml2: 2.9.10_2
output from the command
`pkg-config --cflags xmlsec1`
output:
-D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -I/home/linuxbrew/.linuxbrew/Cellar/libxmlsec1/1.2.31/include/xmlsec1 -I/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include -I/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include/openssl -I/home/linuxbrew/.linuxbrew/Cellar/libxslt/1.1.34_3/include -I/home/linuxbrew/.linuxbrew/Cellar/libxml2/2.9.10_2/include/libxml2

crash reporters:
make bootstrapWithOutDevlop
sentry init --dev
File already exists at '/home/vidy/.sentry/config.yml', overwrite? [y/N]: y
File already exists at '/home/vidy/.sentry/sentry.conf.py', overwrite? [y/N]: y
sentry devservices up
06:03:34 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
Traceback (most recent call last):
  File "/mnt/e/study/sentry/sentry/.venv/bin/sentry", line 33, in <module>
    sys.exit(load_entry_point('sentry', 'console_scripts', 'sentry')())
  File "/mnt/e/study/sentry/sentry/src/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/mnt/e/study/sentry/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/e/study/sentry/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mnt/e/study/sentry/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/e/study/sentry/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/e/study/sentry/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/e/study/sentry/sentry/.venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/e/study/sentry/sentry/.venv/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/e/study/sentry/sentry/src/sentry/runner/commands/devservices.py", line 179, in up
    configure()
  File "/mnt/e/study/sentry/sentry/src/sentry/runner/__init__.py", line 129, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/mnt/e/study/sentry/sentry/src/sentry/runner/settings.py", line 158, in configure
    skip_service_validation=skip_service_validation,
  File "/mnt/e/study/sentry/sentry/src/sentry/runner/initializer.py", line 338, in initialize_app
    django.setup()
  File "/mnt/e/study/sentry/sentry/.venv/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/mnt/e/study/sentry/sentry/.venv/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/mnt/e/study/sentry/sentry/src/sentry/auth/providers/saml2/activedirectory/apps.py", line 12, in ready
    from .provider import ActiveDirectorySAML2Provider
  File "/mnt/e/study/sentry/sentry/src/sentry/auth/providers/saml2/activedirectory/provider.py", line 3, in <module>
    from sentry.auth.providers.saml2.generic.provider import GenericSAML2Provider
  File "/mnt/e/study/sentry/sentry/src/sentry/auth/providers/saml2/generic/provider.py", line 3, in <module>
    from sentry.auth.providers.saml2.provider import SAML2Provider
  File "/mnt/e/study/sentry/sentry/src/sentry/auth/providers/saml2/provider.py", line 28, in <module>
    from onelogin.saml2.auth import OneLogin_Saml2_Auth, OneLogin_Saml2_Settings
  File "/mnt/e/study/sentry/sentry/.venv/lib/python3.6/site-packages/onelogin/saml2/auth.py", line 14, in <module>
    import xmlsec
xmlsec.Error: (19, 'xmlsec library version mismatch.')
make: *** [Makefile:30: run-dependent-services] Error 1
![image](https://user-images.githubusercontent.com/10415170/104151595-70011700-5418-11eb-8a98-6a37136f1698.png)

**Comment by utiq** [comment]
@boneVidy I'm having the same error, how did you solve it?

**Comment by utiq** [comment]
@hoefling Awesome, thanks for your help, I uninstalled and re-installed the package and now it works like a charm.

**Comment by hoefling** [comment]
Will close this as the reinstall solution is confirmed. @boneVidy feel free to ping me if the issue should be reopened, though.
