### ISSUE TITLE
Not able to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by sagrawal-code** [mehcode/python-xmlsec#194]
Till yesterday, I was able to install without any hitch.
Today, installation failing with following error:

```
python3.8 -m pip install xmlsec
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting xmlsec
  Downloading https://files.pythonhosted.org/packages/ff/dd/0893ae620bfe3537eaa91c3a24e70dceba616b0cc71ed8e9fe9d0289fe34/xmlsec-1.3.11.tar.gz (61kB)
    100% |████████████████████████████████| 61kB 9.8MB/s 
    Complete output from command python setup.py egg_info:
    /home/ubuntu/.local/lib/python3.8/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      warnings.warn(
    /home/ubuntu/.local/lib/python3.8/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'build-requires' will not be supported in future versions. Please use the underscore name 'build_requires' instead
      warnings.warn(
    /home/ubuntu/.local/lib/python3.8/site-packages/setuptools/dist.py:697: UserWarning: Usage of dash-separated 'upload-dir' will not be supported in future versions. Please use the underscore name 'upload_dir' instead
      warnings.warn(
    /home/ubuntu/.local/lib/python3.8/site-packages/setuptools_scm/integration.py:54: UserWarning: pyproject.toml does not contain a tool.setuptools_scm section
      warnings.warn(str(e))
    Traceback (most recent call last):
      File "/home/ubuntu/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2739, in requires
        deps.extend(dm[safe_extra(ext)])
    KeyError: 'toml'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yd502rnr/xmlsec/setup.py", line 400, in <module>
        setup(
      File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/ubuntu/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        new_requirements = dist.requires(req.extras)[::-1]
      File "/home/ubuntu/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2741, in requires
        raise UnknownExtra(
    pkg_resources.UnknownExtra: setuptools-scm 6.2.0 has no such extra feature 'toml'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yd502rnr/xmlsec/
```

I am sorry, but I am not able to figure out why this is failing as all relevant packages as detailed in the documentation as dependencies seem to be installed. If anyone can provide some hints, it will be very helpful.

Thank you!

**Comment by hoefling** [comment]
@sagrawal-code try downgrading `setuptools-scm` back to 6.0.1. The 6.2.0 is borked, see https://github.com/pypa/setuptools_scm/issues/611, https://github.com/pypa/setuptools_scm/issues/612, https://github.com/pypa/setuptools_scm/issues/613 etc.

**Comment by sagrawal-code** [comment]
Thank you so much for your quick reply! It helped.
