### ISSUE TITLE
Docker build just started failing

### ISSUE THREAD

**Issue by catmeme** [mehcode/python-xmlsec#31]
For months, we've had a docker image that uses xmlsec that worked flawlessly. This morning, a few developers tried rebuilding and started receiving the following error:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7q8jv7dq/xmlsec/setup.py", line 123, in <module>
        make_extension('xmlsec.template'),
      File "/usr/local/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 195, in run
        self.find_sources()
      File "/usr/local/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 222, in find_sources
        mm.run()
      File "/usr/local/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 306, in run
        self.add_defaults()
      File "/usr/local/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 335, in add_defaults
        sdist.add_defaults(self)
      File "/usr/local/lib/python3.4/site-packages/setuptools/command/sdist.py", line 171, in add_defaults
        build_ext = self.get_finalized_command('build_ext')
      File "/usr/local/lib/python3.4/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/local/lib/python3.4/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-7q8jv7dq/xmlsec/.eggs/Cython-0.25a0-py3.4-linux-x86_64.egg/Cython/Distutils/build_ext.py", line 19, in finalize_options
        self.distribution.ext_modules)
      File "/tmp/pip-build-7q8jv7dq/xmlsec/.eggs/Cython-0.25a0-py3.4-linux-x86_64.egg/Cython/Build/Dependencies.py", line 809, in cythonize
        aliases=aliases)
      File "/tmp/pip-build-7q8jv7dq/xmlsec/.eggs/Cython-0.25a0-py3.4-linux-x86_64.egg/Cython/Build/Dependencies.py", line 752, in create_extension_list
        **kwds))
    TypeError: __init__() got an unexpected keyword argument 'sources'
    src/xmlsec/constants.pyx: cannot find cimported module '.utils'
    src/xmlsec/constants.pyx: cannot find cimported module '.constants'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7q8jv7dq/xmlsec/
Traceback (most recent call last):
  File "/usr/local/bin/pip-sync", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/piptools/scripts/sync.py", line 72, in cli
    install_flags=install_flags))
  File "/usr/local/lib/python3.4/site-packages/piptools/sync.py", line 157, in sync
    check_call([pip, 'install'] + pip_flags + install_flags + sorted(to_install))
  File "/usr/local/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/pip', 'install', 'Jinja2==2.8', 'Mako==1.0.4', 'MarkupSafe==0.23', 'Pygments==2.1.3', 'SQLAlchemy==1.0.14', 'WebOb==1.6.1', 'alabaster==0.7.9', 'alembic==0.8.7', 'argparse==1.4.0', 'babel==2.3.4', 'beautifulsoup4==4.5.0', 'boto3==1.3.1', 'botocore==1.4.40', 'cffi==1.7.0', 'cryptography==1.4', 'cython==0.24.1', 'decorator==4.0.10', 'defusedxml==0.4.1', 'docutils==0.12', 'dogpile.cache==0.6.1', 'ecdsa==0.13', 'et-xmlfile==1.0.1', 'extras==1.0.0', 'falcon==1.0.0', 'fixtures==3.0.0', 'future==0.15.2', 'gunicorn==19.6.0', 'hg+https://bitbucket.org/jurko/suds#egg=suds-jurko', 'hypothesis==3.4.2', 'idna==2.1', 'imagesize==0.7.1', 'isodate==0.5.4', 'jdcal==1.2', 'jmespath==0.9.0', 'linecache2==1.0.0', 'lxml==3.6.1', 'marshmallow==2.9.1', 'mox3==0.17.0', 'multipart==0.1', 'openpyxl==2.3.5', 'paramiko==2.0.2', 'paste==2.0.3', 'pbr==1.10.0', 'pillow==3.3.0', 'psycopg2==2.6.2', 'py==1.4.31', 'pyOpenSSL==16.0.0', 'pyasn1==0.1.9', 'pycountry==1.20', 'pycparser==2.14', 'pycrypto==2.6.1', 'pyfakefs==2.7', 'pylibmc==1.5.1', 'pymssql==2.1.3', 'pymysql==0.7.5', 'pyodbc==3.0.10', 'pysaml2==4.0.1', 'pytest==2.9.2', 'python-dateutil==2.5.3', 'python-editor==1.0.1', 'python-jose==1.1.0', 'python-magic==0.4.12', 'python-mimeparse==1.5.2', 'python3-saml==1.1.4', 'pytz==2016.6.1', 'repoze.who==2.3', 'requests==2.10.0', 'simplejson==3.8.2', 'snowballstemmer==1.2.1', 'sphinx-autodoc-annotation==1.0', 'sphinx==1.4.5', 'sqlparse==0.2.0', 'sqltap==0.3.10', 'testtools==2.2.0', 'traceback2==1.4.0', 'typing==3.5.2.2', 'unittest2==1.1.0', 'waitress==0.9.0', 'webtest==2.0.23', 'werkzeug==0.11.10', 'xmlsec==0.6.1', 'zope.interface==4.2.0']' returned non-zero exit status 1
ERROR: Service 'app_web' failed to build: The command '/bin/sh -c pip install --upgrade pip && pip install --upgrade setuptools && pip install pip-tools && pip-sync prod-requirements.txt requirements.txt dev-requirements.txt' returned a non-zero code: 1
```

Python: 3.4.4
Pip: 8.1.2
Setuptools: 18.2

Here's an excerpt from our Dockerfile to give you an idea of what we're doing:

```
FROM python:3.4.4

RUN mkdir /application
WORKDIR /application

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates build-essential python3-setuptools python3-dev libpq-dev libxml2-dev xmlsec1 libxmlsec1-dev libxslt1-dev libffi-dev libjpeg-dev libmemcached-dev freetds-dev unixodbc unixodbc-dev mercurial postgresql-client mysql-client \
    && apt-get clean

RUN pyvenv venv
COPY build/requirements.txt ./requirements.txt
COPY build/prod-requirements.txt ./prod-requirements.txt
COPY build/dev-requirements.txt ./dev-requirements.txt
RUN pip install --upgrade pip && pip install pip-tools && pip-sync prod-requirements.txt requirements.txt dev-requirements.txt
```

We also tried adding the following deps: `python-lxml, libxmlsec1-openssl pkg-config` to no avail.

**Comment by yannispanousis** [comment]
+1

**Comment by mbarrien** [comment]
Cython just released a version 0.25a0 that appears to be killing out builds. https://groups.google.com/forum/#!topic/cython-users/558LV9YnW7g seems to indicate they think this is an alpha version that shouldn't be pulled in, but obviously this isn't the case.

**Comment by catmeme** [comment]
Any recommendations on versions we should pin?

Cython, python-xmlsec and pysaml2?

**Comment by yannispanousis** [comment]
`Cython==0.24.1` works for me. But the only way I could install it was via `easy_install` and not `pip`.

So my workaround was:

```
easy_install Cython==0.24.1
pip install python3-saml
```

**Comment by catmeme** [comment]
hmm, thanks @yannispanousis but here's what I have in my requirements.txt after pip-compile:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
-e hg+https://bitbucket.org/jurko/suds#egg=suds-jurko
alembic==0.8.7
babel==2.3.4
boto3==1.3.1
botocore==1.4.40          # via boto3
cffi==1.7.0               # via cryptography
click==6.6
cryptography==1.4         # via paramiko, pyopenssl
cython==0.24.1
decorator==4.0.10         # via pysaml2
defusedxml==0.4.1
docutils==0.12            # via botocore
dogpile.cache==0.6.1
ecdsa==0.13               # via python-jose
et-xmlfile==1.0.1         # via openpyxl
falcon==1.0.0
future==0.15.2            # via python-jose
gunicorn==19.6.0
idna==2.1                 # via cryptography
isodate==0.5.4            # via python3-saml
jdcal==1.2                # via openpyxl
jinja2==2.8
jmespath==0.9.0           # via boto3, botocore
lxml==3.6.1               # via xmlsec
Mako==1.0.4               # via alembic
MarkupSafe==0.23          # via jinja2, mako
marshmallow==2.9.1
multipart==0.1
openpyxl==2.3.5
paramiko==2.0.2
paste==2.0.3              # via pysaml2
pillow==3.3.0
psycopg2==2.6.2
pyasn1==0.1.9             # via cryptography, paramiko
pycountry==1.20
pycparser==2.14           # via cffi
pycrypto==2.6.1           # via pysaml2, python-jose
pylibmc==1.5.1
pymssql==2.1.3
pymysql==0.7.5
pyodbc==3.0.10
pyOpenSSL==16.0.0         # via pysaml2
pysaml2==4.0.1
python-dateutil==2.5.3
python-editor==1.0.1      # via alembic
python-jose==1.1.0
python-magic==0.4.12
python-mimeparse==1.5.2   # via falcon
python3-saml==1.1.4
pytz==2016.6.1            # via babel, pysaml2
repoze.who==2.3           # via pysaml2
requests==2.10.0
simplejson==3.8.2
six==1.10.0               # via cryptography, falcon, paste, pyopenssl, pysaml2, python-dateutil, python-jose
sqlalchemy==1.0.14
typing==3.5.2.2
WebOb==1.6.1              # via repoze.who
xmlsec==0.6.1             # via python3-saml
zope.interface==4.2.0     # via pysaml2, repoze.who
```

Before running pip-sync requirements.txt -- looks like I have the proper version pinned but still getting the error.

Any ideas?

**Comment by mbarrien** [comment]
pip installing cython==0.24.1 before installing xmlsec works for me on the platforms I've tested (OS X with Python 3.5 and Ubuntu 12.04 with Python 3.4). Trying to "pip install cython==0.24.1 xmlsec" or install simutaneously in a requirements.txt file seems to fail.

**Comment by catmeme** [comment]
@mbarrien Thanks, installing cython with pip prior to my requirements did it!

**Comment by mbarrien** [comment]
https://groups.google.com/d/msg/cython-users/558LV9YnW7g/Hv0PdvtmAwAJ says that they have withdrawn Cython 0.25a0 from pypi, so this shouldn't be an immediate problem now, since 0.24.1 is the highest version available. However this does point to either python-xmlsec or setuptools_cython using old install tools in its setup.py that don't use modern pip version aware version parsing. This may need an upgrade to stop using ez_install compatible tools which is what broke this.

**Comment by mvid** [comment]
I have this issue, and I am not using Cython.

**Comment by mvid** [comment]
Looks like the new version of Cython, 0.25 

Even when I pin the install version to 0.24.1 it still installs 0.25 during the xmlsec installation.

**Comment by catmeme** [comment]
@mvid, I had to `pip install cython==0.24.1`, then install my requirements per @mbarrien's comments above, "install simultaneously in a requirements.txt file seems to fail"

My Dockerfile now contains:

```
RUN pip install --upgrade pip && \
    pip install pip-tools && \
    pip install cython==0.24.1

RUN pip-compile requirements.in && \
    pip-compile prod-requirements.in && \
    pip-compile dev-requirements.in

RUN pip-sync prod-requirements.txt requirements.txt dev-requirements.txt
```

**Comment by mvid** [comment]
@catmeme yea that works for me now. Thanks! 

This still seems like an issue with xmlsec though.

**Comment by bgaifullin** [comment]
The python-xmlsec was rewritten on pure C and there is no more cython is required for building. 
I close this bug because it is not obsolete.
