### ISSUE TITLE
Build error on Python 3.4 on CentOS 7

### ISSUE THREAD

**Issue by discretepackets** [mehcode/python-xmlsec#75]
For Python 3 on CentOS 7, the default on CentOS 7 is Python 3.4 and attempting to build will result in this error below:

```
# python3 setup.py build
running build
running build_ext
Traceback (most recent call last):
  File "setup.py", line 60, in <module>
    'Topic :: Text Processing :: Markup :: XML'
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.4/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 11, in run
    self.patch_options()
  File "setup.py", line 16, in patch_options
    ext.define_macros.extend(xmlsec_setupinfo.define_macros())
  File "/root/python-xmlsec/xmlsec_setupinfo.py", line 48, in define_macros
    macros.extend(xmlsec_config()['define_macros'])
  File "/root/python-xmlsec/xmlsec_setupinfo.py", line 111, in xmlsec_config
    __XMLSEC_CONFIG = load_xmlsec1_config()
  File "/root/python-xmlsec/xmlsec_setupinfo.py", line 178, in load_xmlsec1_config
    macros[i] = ('XMLSEC_CRYPTO', '"{0}"'.format(v[1]))
TypeError: 'set' object does not support item assignment
```
I tried the same build process with Python 3.6 instead and it built successfully.

**Comment by discretepackets** [comment]
Interestingly, I don't get the error if I install a newer version of Python 3.4 from `https://centos7.iuscommunity.org/ius-release.rpm` It might be a bug related to the language version.

**Comment by bgaifullin** [comment]
I committed fix, could you please confirm that it resolves this issue.

**Comment by bgaifullin** [comment]
do updates for long time. close the issue
