### ISSUE TITLE
Could not find xmlsec1 config

### ISSUE THREAD

**Issue by jasonmarkperez** [mehcode/python-xmlsec#92]
Hello,

I've been unable to install xmlsec as a requirement for a project I'm working with. I've also tried to do a clone and install of just python-xmlsec, which fails in the same way.

**Python**: 3.6.0 (using pyenv)
Verified I have brew installed libxml2 and libxmlsec1.

```
 Created temporary directory: /private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-record-ivlqt5k_
  Running setup.py install for xmlsec ...     Running command /Users/jperez/.pyenv/versions/3.6.0/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-install-ouu8wmuk/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-record-ivlqt5k_/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_ext
    *********************************************************************************
    Could not find xmlsec1 config. Are libxmlsec1-dev and pkg-config installed?
    Perhaps try: xcode-select --install
    *********************************************************************************
error
Cleaning up...
  Removing source in /private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-install-ouu8wmuk/python-ldap
  Removing source in /private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-install-ouu8wmuk/xmlsec
Removed build tracker '/private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-req-tracker-cqb9uyzl'
Command "/Users/jperez/.pyenv/versions/3.6.0/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-install-ouu8wmuk/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-record-ivlqt5k_/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-install-ouu8wmuk/xmlsec/
Exception information:
Traceback (most recent call last):
  File "/Users/jperez/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/Users/jperez/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "/Users/jperez/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/Users/jperez/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 791, in install
    spinner=spinner,
  File "/Users/jperez/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/Users/jperez/.pyenv/versions/3.6.0/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-install-ouu8wmuk/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-record-ivlqt5k_/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/hv/46x2kc_97mqgpsqlrlndm5m400062y/T/pip-install-ouu8wmuk/xmlsec/
```
I tried uninstall and reinstalling libxml2 and libxmlsec1, upgraded xcode to 10.1. Any idea what might be going on?

**Comment by bgaifullin** [comment]
do you install pkg-config as well?

**Comment by lovegandhi** [comment]
@bgaifullin  I tried to follow the instructions from readme file just as @jasonmarkperez and received the above message.
What fixed it for me was: `brew install libxml2 libxmlsec1 pkg-config`
Perhaps the readme should be updated to include pkg-config as a requirement?

**Comment by bgaifullin** [comment]
yes. there is also PR for this #66, but it is not completed yet. 
I would be happy to accept PR which adds this to READE and setup instructions
