### ISSUE TITLE
Error when installing via pip in Django 2.7

### ISSUE THREAD

**Issue by jpmeatme** [mehcode/python-xmlsec#99]
Hi, i am having this issue. I am using AWS Elastic Beanstalk

Collecting xmlsec<1,>=0.6.0 (from py-wsse->-r /opt/python/ondeck/app/requirements.txt (line 78))
  Downloading https://files.pythonhosted.org/packages/e1/ec/0330f39bc5eb270b6b62a9dbb11194c6d4215b48ef8d04c78a30dc1d2d1d/xmlsec-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    src/lxml/etree.c: In function '__Pyx_PyUnicode_From_xmlElementType':
    src/lxml/etree.c:241793: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c:241794: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c:241798: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c: In function '__Pyx_PyUnicode_From_Py_ssize_t':
    src/lxml/etree.c:242188: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c:242189: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c:242193: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c: In function '__Pyx_PyUnicode_From_int':
    src/lxml/etree.c:242382: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c:242383: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c:242387: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c: In function '__Pyx_PyUnicode_From_xmlXPathObjectType':
    src/lxml/etree.c:245038: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c:245039: error: #pragma GCC diagnostic not allowed inside functions
    src/lxml/etree.c:245043: error: #pragma GCC diagnostic not allowed inside functions
    Building lxml version 4.3.1.
    Building without Cython.
    ERROR: /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    /bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt 1.1.28
    Building against libxml2/libxslt in the following directory: /usr/lib64
    Compile failed: command 'gcc' failed with exit status 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-WEzAOh/xmlsec/setup.py", line 123, in <module>
        make_extension('xmlsec.template'),
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 638, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 668, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 851, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1079, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1067, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by hoefling** [comment]
`xmlsec==0.6.1` is outdated; I'd ask the maintainer of `py-wsse` to update by [opening a new issue in that project](https://github.com/orcasgit/py-wsse/issues/new).
